# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: llm_gateway.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Optional

import betterproto
import grpclib

from .google import protobuf


@dataclass
class GenerateTextRequest(betterproto.Message):
    version: str = betterproto.string_field(1)
    model_name: str = betterproto.string_field(2)
    prompt: str = betterproto.string_field(3)
    localization: protobuf.Struct = betterproto.message_field(4)
    tags: protobuf.Struct = betterproto.message_field(5)



