name: Lint and Test

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies (with dev)
      run: poetry install --with dev --no-interaction

    - name: Run lint
      run: make lint

    - name: Run tests
      run: make test
